# Codacy configuration for excluding files and folders from analysis
# https://docs.codacy.com/repositories-configure/codacy-configuration-file/#ignore-files
# Uses Java glob syntax: https://docs.oracle.com/javase/tutorial/essential/io/fileOps.html#glob

exclude_paths:

  # Ignore all root-level metadata and documentation
  - '.gitignore'
  - '.runsettings'
  - 'LICENSE'
  - 'README.md'

  # Ignore all file types that shouldn't be analyzed
  - '**.yml'
  - '**.json'
  - '**.png'
  - '**.sln'
  - '**.csproj'

  # Ignore generated or infrastructure files
  - '**/*Program.cs'

  # Ignore specific folders across any depth in the project
  - '**/Configurations/**'
  - '**/Data/**'
  - '**/Enums/**'
  - '**/Extensions/**'
  - '**/Mappings/**'
  - '**/Migrations/**'
  - '**/Models/**'
  - '**/Properties/**'
  - '**/Repositories/**'
  - '**/Utilities/**'
  - '**/Validators/**'
  - 'test/**/*'
  - 'scripts/**/*'
