// <auto-generated />
using System;
using Dotnet.Samples.AspNetCore.WebApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Dotnet.Samples.AspNetCore.WebApi.Migrations
{
    [DbContext(typeof(PlayerDbContext))]
    [Migration("20260409141707_SeedStarting11")]
    partial class SeedStarting11
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("Dotnet.Samples.AspNetCore.WebApi.Models.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AbbrPosition")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("League")
                        .HasColumnType("TEXT");

                    b.Property<string>("MiddleName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Position")
                        .HasColumnType("TEXT");

                    b.Property<int>("SquadNumber")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Starting11")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Team")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SquadNumber")
                        .IsUnique();

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            Id = new Guid("01772c59-43f0-5d85-b913-c78e4e281452"),
                            AbbrPosition = "GK",
                            DateOfBirth = new DateTime(1992, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "Damián",
                            LastName = "Martínez",
                            League = "Premier League",
                            MiddleName = "Emiliano",
                            Position = "Goalkeeper",
                            SquadNumber = 23,
                            Starting11 = true,
                            Team = "Aston Villa FC"
                        },
                        new
                        {
                            Id = new Guid("da31293b-4c7e-5e0f-a168-469ee29ecbc4"),
                            AbbrPosition = "RB",
                            DateOfBirth = new DateTime(1998, 4, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "Nahuel",
                            LastName = "Molina",
                            League = "La Liga",
                            Position = "Right-Back",
                            SquadNumber = 26,
                            Starting11 = true,
                            Team = "Altético Madrid"
                        },
                        new
                        {
                            Id = new Guid("c096c69e-762b-5281-9290-bb9c167a24a0"),
                            AbbrPosition = "CB",
                            DateOfBirth = new DateTime(1998, 4, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "Cristian",
                            LastName = "Romero",
                            League = "Premier League",
                            MiddleName = "Gabriel",
                            Position = "Centre-Back",
                            SquadNumber = 13,
                            Starting11 = true,
                            Team = "Tottenham Hotspur"
                        },
                        new
                        {
                            Id = new Guid("d5f7dd7a-1dcb-5960-ba27-e34865b63358"),
                            AbbrPosition = "CB",
                            DateOfBirth = new DateTime(1988, 2, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "Nicolás",
                            LastName = "Otamendi",
                            League = "Liga Portugal",
                            MiddleName = "Hernán Gonzalo",
                            Position = "Centre-Back",
                            SquadNumber = 19,
                            Starting11 = true,
                            Team = "SL Benfica"
                        },
                        new
                        {
                            Id = new Guid("2f6f90a0-9b9d-5023-96d2-a2aaf03143a6"),
                            AbbrPosition = "LB",
                            DateOfBirth = new DateTime(1992, 8, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "Nicolás",
                            LastName = "Tagliafico",
                            League = "Ligue 1",
                            MiddleName = "Alejandro",
                            Position = "Left-Back",
                            SquadNumber = 3,
                            Starting11 = true,
                            Team = "Olympique Lyon"
                        },
                        new
                        {
                            Id = new Guid("b5b46e79-929e-5ed2-949d-0d167109c022"),
                            AbbrPosition = "RW",
                            DateOfBirth = new DateTime(1988, 2, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "Ángel",
                            LastName = "Di María",
                            League = "Liga Portugal",
                            MiddleName = "Fabián",
                            Position = "Right Winger",
                            SquadNumber = 11,
                            Starting11 = true,
                            Team = "SL Benfica"
                        },
                        new
                        {
                            Id = new Guid("0293b282-1da8-562e-998e-83849b417a42"),
                            AbbrPosition = "CM",
                            DateOfBirth = new DateTime(1994, 5, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "Rodrigo",
                            LastName = "de Paul",
                            League = "La Liga",
                            MiddleName = "Javier",
                            Position = "Central Midfield",
                            SquadNumber = 7,
                            Starting11 = true,
                            Team = "Altético Madrid"
                        },
                        new
                        {
                            Id = new Guid("d3ba552a-dac3-588a-b961-1ea7224017fd"),
                            AbbrPosition = "CM",
                            DateOfBirth = new DateTime(2001, 1, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "Enzo",
                            LastName = "Fernández",
                            League = "Liga Portugal",
                            MiddleName = "Jeremías",
                            Position = "Central Midfield",
                            SquadNumber = 24,
                            Starting11 = true,
                            Team = "SL Benfica"
                        },
                        new
                        {
                            Id = new Guid("9613cae9-16ab-5b54-937e-3135123b9e0d"),
                            AbbrPosition = "CM",
                            DateOfBirth = new DateTime(1998, 12, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "Alexis",
                            LastName = "Mac Allister",
                            League = "Premier League",
                            Position = "Central Midfield",
                            SquadNumber = 20,
                            Starting11 = true,
                            Team = "Brighton & Hove Albion"
                        },
                        new
                        {
                            Id = new Guid("acc433bf-d505-51fe-831e-45eb44c4d43c"),
                            AbbrPosition = "RW",
                            DateOfBirth = new DateTime(1987, 6, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "Lionel",
                            LastName = "Messi",
                            League = "Ligue 1",
                            MiddleName = "Andrés",
                            Position = "Right Winger",
                            SquadNumber = 10,
                            Starting11 = true,
                            Team = "Paris Saint-Germain"
                        },
                        new
                        {
                            Id = new Guid("38bae91d-8519-55a2-b30a-b9fe38849bfb"),
                            AbbrPosition = "CF",
                            DateOfBirth = new DateTime(2000, 1, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "Julián",
                            LastName = "Álvarez",
                            League = "Premier League",
                            Position = "Centre-Forward",
                            SquadNumber = 9,
                            Starting11 = true,
                            Team = "Manchester City"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
