// <auto-generated />
using System;
using Dotnet.Samples.AspNetCore.WebApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Dotnet.Samples.AspNetCore.WebApi.Migrations
{
    [DbContext(typeof(PlayerDbContext))]
    [Migration("20260409141721_SeedSubstitutes")]
    partial class SeedSubstitutes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("Dotnet.Samples.AspNetCore.WebApi.Models.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AbbrPosition")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("League")
                        .HasColumnType("TEXT");

                    b.Property<string>("MiddleName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Position")
                        .HasColumnType("TEXT");

                    b.Property<int>("SquadNumber")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Starting11")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Team")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SquadNumber")
                        .IsUnique();

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            Id = new Guid("01772c59-43f0-5d85-b913-c78e4e281452"),
                            AbbrPosition = "GK",
                            DateOfBirth = new DateTime(1992, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "Damián",
                            LastName = "Martínez",
                            League = "Premier League",
                            MiddleName = "Emiliano",
                            Position = "Goalkeeper",
                            SquadNumber = 23,
                            Starting11 = true,
                            Team = "Aston Villa FC"
                        },
                        new
                        {
                            Id = new Guid("da31293b-4c7e-5e0f-a168-469ee29ecbc4"),
                            AbbrPosition = "RB",
                            DateOfBirth = new DateTime(1998, 4, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "Nahuel",
                            LastName = "Molina",
                            League = "La Liga",
                            Position = "Right-Back",
                            SquadNumber = 26,
                            Starting11 = true,
                            Team = "Altético Madrid"
                        },
                        new
                        {
                            Id = new Guid("c096c69e-762b-5281-9290-bb9c167a24a0"),
                            AbbrPosition = "CB",
                            DateOfBirth = new DateTime(1998, 4, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "Cristian",
                            LastName = "Romero",
                            League = "Premier League",
                            MiddleName = "Gabriel",
                            Position = "Centre-Back",
                            SquadNumber = 13,
                            Starting11 = true,
                            Team = "Tottenham Hotspur"
                        },
                        new
                        {
                            Id = new Guid("d5f7dd7a-1dcb-5960-ba27-e34865b63358"),
                            AbbrPosition = "CB",
                            DateOfBirth = new DateTime(1988, 2, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "Nicolás",
                            LastName = "Otamendi",
                            League = "Liga Portugal",
                            MiddleName = "Hernán Gonzalo",
                            Position = "Centre-Back",
                            SquadNumber = 19,
                            Starting11 = true,
                            Team = "SL Benfica"
                        },
                        new
                        {
                            Id = new Guid("2f6f90a0-9b9d-5023-96d2-a2aaf03143a6"),
                            AbbrPosition = "LB",
                            DateOfBirth = new DateTime(1992, 8, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "Nicolás",
                            LastName = "Tagliafico",
                            League = "Ligue 1",
                            MiddleName = "Alejandro",
                            Position = "Left-Back",
                            SquadNumber = 3,
                            Starting11 = true,
                            Team = "Olympique Lyon"
                        },
                        new
                        {
                            Id = new Guid("b5b46e79-929e-5ed2-949d-0d167109c022"),
                            AbbrPosition = "RW",
                            DateOfBirth = new DateTime(1988, 2, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "Ángel",
                            LastName = "Di María",
                            League = "Liga Portugal",
                            MiddleName = "Fabián",
                            Position = "Right Winger",
                            SquadNumber = 11,
                            Starting11 = true,
                            Team = "SL Benfica"
                        },
                        new
                        {
                            Id = new Guid("0293b282-1da8-562e-998e-83849b417a42"),
                            AbbrPosition = "CM",
                            DateOfBirth = new DateTime(1994, 5, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "Rodrigo",
                            LastName = "de Paul",
                            League = "La Liga",
                            MiddleName = "Javier",
                            Position = "Central Midfield",
                            SquadNumber = 7,
                            Starting11 = true,
                            Team = "Altético Madrid"
                        },
                        new
                        {
                            Id = new Guid("d3ba552a-dac3-588a-b961-1ea7224017fd"),
                            AbbrPosition = "CM",
                            DateOfBirth = new DateTime(2001, 1, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "Enzo",
                            LastName = "Fernández",
                            League = "Liga Portugal",
                            MiddleName = "Jeremías",
                            Position = "Central Midfield",
                            SquadNumber = 24,
                            Starting11 = true,
                            Team = "SL Benfica"
                        },
                        new
                        {
                            Id = new Guid("9613cae9-16ab-5b54-937e-3135123b9e0d"),
                            AbbrPosition = "CM",
                            DateOfBirth = new DateTime(1998, 12, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "Alexis",
                            LastName = "Mac Allister",
                            League = "Premier League",
                            Position = "Central Midfield",
                            SquadNumber = 20,
                            Starting11 = true,
                            Team = "Brighton & Hove Albion"
                        },
                        new
                        {
                            Id = new Guid("acc433bf-d505-51fe-831e-45eb44c4d43c"),
                            AbbrPosition = "RW",
                            DateOfBirth = new DateTime(1987, 6, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "Lionel",
                            LastName = "Messi",
                            League = "Ligue 1",
                            MiddleName = "Andrés",
                            Position = "Right Winger",
                            SquadNumber = 10,
                            Starting11 = true,
                            Team = "Paris Saint-Germain"
                        },
                        new
                        {
                            Id = new Guid("38bae91d-8519-55a2-b30a-b9fe38849bfb"),
                            AbbrPosition = "CF",
                            DateOfBirth = new DateTime(2000, 1, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "Julián",
                            LastName = "Álvarez",
                            League = "Premier League",
                            Position = "Centre-Forward",
                            SquadNumber = 9,
                            Starting11 = true,
                            Team = "Manchester City"
                        },
                        new
                        {
                            Id = new Guid("5a9cd988-95e6-54c1-bc34-9aa08acca8d0"),
                            AbbrPosition = "GK",
                            DateOfBirth = new DateTime(1986, 10, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "Franco",
                            LastName = "Armani",
                            League = "Copa de la Liga",
                            MiddleName = "Daniel",
                            Position = "Goalkeeper",
                            SquadNumber = 1,
                            Starting11 = false,
                            Team = "River Plate"
                        },
                        new
                        {
                            Id = new Guid("c62f2ac1-41e8-5d34-b073-2ba0913d0e31"),
                            AbbrPosition = "GK",
                            DateOfBirth = new DateTime(1992, 5, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "Gerónimo",
                            LastName = "Rulli",
                            League = "Eredivisie",
                            Position = "Goalkeeper",
                            SquadNumber = 12,
                            Starting11 = false,
                            Team = "Ajax Amsterdam"
                        },
                        new
                        {
                            Id = new Guid("5fdb10e8-38c0-5084-9a3f-b369a960b9c2"),
                            AbbrPosition = "RB",
                            DateOfBirth = new DateTime(1998, 1, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "Juan",
                            LastName = "Foyth",
                            League = "La Liga",
                            MiddleName = "Marcos",
                            Position = "Right-Back",
                            SquadNumber = 2,
                            Starting11 = false,
                            Team = "Villarreal"
                        },
                        new
                        {
                            Id = new Guid("bbd441f7-fcfb-5834-8468-2a9004b64c8c"),
                            AbbrPosition = "RB",
                            DateOfBirth = new DateTime(1997, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "Gonzalo",
                            LastName = "Montiel",
                            League = "Premier League",
                            MiddleName = "Ariel",
                            Position = "Right-Back",
                            SquadNumber = 4,
                            Starting11 = false,
                            Team = "Nottingham Forest"
                        },
                        new
                        {
                            Id = new Guid("d8bfea25-f189-5d5e-b3a5-ed89329b9f7c"),
                            AbbrPosition = "CB",
                            DateOfBirth = new DateTime(1991, 6, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "Germán",
                            LastName = "Pezzella",
                            League = "La Liga",
                            MiddleName = "Alejo",
                            Position = "Centre-Back",
                            SquadNumber = 6,
                            Starting11 = false,
                            Team = "Real Betis Balompié"
                        },
                        new
                        {
                            Id = new Guid("dca343a8-12e5-53d6-89a8-916b120a5ee4"),
                            AbbrPosition = "LB",
                            DateOfBirth = new DateTime(1991, 10, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "Marcos",
                            LastName = "Acuña",
                            League = "La Liga",
                            MiddleName = "Javier",
                            Position = "Left-Back",
                            SquadNumber = 8,
                            Starting11 = false,
                            Team = "Sevilla FC"
                        },
                        new
                        {
                            Id = new Guid("98306555-a466-5d18-804e-dc82175e697b"),
                            AbbrPosition = "CB",
                            DateOfBirth = new DateTime(1998, 1, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "Lisandro",
                            LastName = "Martínez",
                            League = "Premier League",
                            Position = "Centre-Back",
                            SquadNumber = 25,
                            Starting11 = false,
                            Team = "Manchester United"
                        },
                        new
                        {
                            Id = new Guid("9d140400-196f-55d8-86e1-e0b96a375c83"),
                            AbbrPosition = "DM",
                            DateOfBirth = new DateTime(1994, 6, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "Leandro",
                            LastName = "Paredes",
                            League = "Serie A",
                            MiddleName = "Daniel",
                            Position = "Defensive Midfield",
                            SquadNumber = 5,
                            Starting11 = false,
                            Team = "AS Roma"
                        },
                        new
                        {
                            Id = new Guid("d3b0e8e8-2c34-531a-b608-b24fed0ef986"),
                            AbbrPosition = "CM",
                            DateOfBirth = new DateTime(1998, 10, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "Exequiel",
                            LastName = "Palacios",
                            League = "Bundesliga",
                            MiddleName = "Alejandro",
                            Position = "Central Midfield",
                            SquadNumber = 14,
                            Starting11 = false,
                            Team = "Bayer 04 Leverkusen"
                        },
                        new
                        {
                            Id = new Guid("7cc8d527-56a2-58bd-9528-2618fc139d30"),
                            AbbrPosition = "LW",
                            DateOfBirth = new DateTime(1988, 2, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "Alejandro",
                            LastName = "Gómez",
                            League = "Serie A",
                            MiddleName = "Darío",
                            Position = "Left Winger",
                            SquadNumber = 17,
                            Starting11 = false,
                            Team = "AC Monza"
                        },
                        new
                        {
                            Id = new Guid("191c82af-0c51-526a-b903-c3600b61b506"),
                            AbbrPosition = "DM",
                            DateOfBirth = new DateTime(1994, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "Guido",
                            LastName = "Rodríguez",
                            League = "La Liga",
                            Position = "Defensive Midfield",
                            SquadNumber = 18,
                            Starting11 = false,
                            Team = "Real Betis Balompié"
                        },
                        new
                        {
                            Id = new Guid("b1306b7b-a3a4-5f7c-90fd-dd5bdbed57ba"),
                            AbbrPosition = "RW",
                            DateOfBirth = new DateTime(1995, 3, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "Ángel",
                            LastName = "Correa",
                            League = "La Liga",
                            MiddleName = "Martín",
                            Position = "Right Winger",
                            SquadNumber = 15,
                            Starting11 = false,
                            Team = "Atlético Madrid"
                        },
                        new
                        {
                            Id = new Guid("ecec27e8-487b-5622-b116-0855020477ed"),
                            AbbrPosition = "AM",
                            DateOfBirth = new DateTime(2001, 4, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "Thiago",
                            LastName = "Almada",
                            League = "Major League Soccer",
                            MiddleName = "Ezequiel",
                            Position = "Attacking Midfield",
                            SquadNumber = 16,
                            Starting11 = false,
                            Team = "Atlanta United FC"
                        },
                        new
                        {
                            Id = new Guid("7941cd7c-4df1-5952-97e8-1e7f5d08e8aa"),
                            AbbrPosition = "SS",
                            DateOfBirth = new DateTime(1993, 11, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "Paulo",
                            LastName = "Dybala",
                            League = "Serie A",
                            MiddleName = "Exequiel",
                            Position = "Second Striker",
                            SquadNumber = 21,
                            Starting11 = false,
                            Team = "AS Roma"
                        },
                        new
                        {
                            Id = new Guid("79c96f29-c59f-5f98-96b8-3a5946246624"),
                            AbbrPosition = "CF",
                            DateOfBirth = new DateTime(1997, 8, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "Lautaro",
                            LastName = "Martínez",
                            League = "Serie A",
                            MiddleName = "Javier",
                            Position = "Centre-Forward",
                            SquadNumber = 22,
                            Starting11 = false,
                            Team = "Inter Milan"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
